/**
 * Every page has its own social card, generated by `bun run og` and served
 * from `static/og/`. Route path and file name are derived from each other here
 * so the generator and the meta tags can never drift apart.
 */
export const OG_TYPE = 'image/jpeg';
export const OG_WIDTH = 1200;
export const OG_HEIGHT = 630;

export function ogImagePath(path: string): string {
	const trimmed = path.replace(/\/+$/, '');
	const slug = trimmed === '' ? 'home' : trimmed.replace(/^\//, '').replace(/\//g, '-');
	return `/og/${slug}.jpg`;
}
