/**
 * Bakes the world outline into `src/lib/data/world-outline.ts`.
 *
 * Boundaries: Natural Earth 1:110m (public domain) from the `world-atlas`
 * module. Projection: Equal Earth (Šavrič, Patterson & Jenny 2018).
 *
 * The app draws the map from the emitted path strings and projects language
 * coordinates with the Equal Earth formula in `src/lib/worldMap.ts`, so the
 * browser never loads d3-geo or the TopoJSON.
 *
 *     bun run geo
 */
import { writeFileSync } from 'node:fs';
import { geoEqualEarth, geoPath, geoGraticule } from 'd3-geo';
import { feature, mesh } from 'topojson-client';
import type { GeometryCollection, Topology } from 'topojson-specification';
import landTopo from 'world-atlas/land-110m.json' with { type: 'json' };
import countriesTopo from 'world-atlas/countries-110m.json' with { type: 'json' };

/** The map shows the inhabited band; Equal Earth smears the poles. */
const SOUTH_EDGE = -56;
const NORTH_EDGE = 80;
const CENTRE_LNG = 10;
const WIDTH = 1000;
const HEIGHT = 460;

const land = landTopo as unknown as Topology<{ land: GeometryCollection }>;
const countries = countriesTopo as unknown as Topology<{ countries: GeometryCollection }>;

function band(): GeoJSON.Polygon {
	const ring: [number, number][] = [];
	for (let lng = -180; lng <= 180; lng += 2) ring.push([lng, NORTH_EDGE]);
	for (let lng = 180; lng >= -180; lng -= 2) ring.push([lng, SOUTH_EDGE]);
	ring.push([-180, NORTH_EDGE]);
	return { type: 'Polygon', coordinates: [ring] };
}

function withoutAntarctica(collection: GeoJSON.FeatureCollection): GeoJSON.FeatureCollection {
	return {
		type: 'FeatureCollection',
		features: collection.features.map((f) =>
			f.geometry.type === 'MultiPolygon'
				? {
						...f,
						geometry: {
							...f.geometry,
							coordinates: f.geometry.coordinates.filter((polygon) =>
								polygon.some((ring) => ring.some(([, lat]) => lat > SOUTH_EDGE))
							)
						}
					}
				: f
		)
	};
}

const projection = geoEqualEarth()
	.rotate([-CENTRE_LNG, 0])
	.fitExtent(
		[
			[0, 0],
			[WIDTH, HEIGHT]
		],
		band()
	);
const path = geoPath(projection);

const landFeature = withoutAntarctica(feature(land, land.objects.land));
const landPath = path(landFeature) ?? '';
const [[x0, y0], [x1, y1]] = path.bounds(landFeature);
const borderPath = mesh(countries, countries.objects.countries, (a, b) => a !== b);
const graticulePath =
	path(
		geoGraticule()
			.extent([
				[-180, SOUTH_EDGE],
				[180, NORTH_EDGE]
			])
			.step([30, 30])()
	) ?? '';

const round = (value: number) => Number(value.toFixed(4));

/** Path coordinates carry more precision than a 1000-unit viewBox can show. */
const trim = (d: string) =>
	d.replace(/-?\d+\.\d+/g, (n) => String(Math.round(Number(n) * 10) / 10));

const file = `// Generated by scripts/geo/build-outline.ts — run \`bun run geo\` to refresh.
// Natural Earth 1:110m boundaries (public domain), Equal Earth projection.

export const world = {
	width: ${WIDTH},
	height: ${HEIGHT},
	centreLng: ${CENTRE_LNG},
	scale: ${round(projection.scale())},
	translate: [${projection.translate().map(round).join(', ')}] as [number, number],
	south: ${SOUTH_EDGE},
	north: ${NORTH_EDGE},
	/** Bounding box of the drawn land, so a frame never slices a coastline. */
	bounds: { x0: ${round(x0)}, y0: ${round(y0)}, x1: ${round(x1)}, y1: ${round(y1)} },
	land: ${JSON.stringify(trim(landPath))},
	borders: ${JSON.stringify(trim(path(borderPath) ?? ''))},
	graticule: ${JSON.stringify(trim(graticulePath))}
};
`;

writeFileSync('src/lib/data/world-outline.ts', file);
console.log(
	`world-outline.ts — land ${landPath.length}B, borders ${(path(borderPath) ?? '').length}B`
);
